Relaunch on crash
CoorpAcademy/kinesis-lambda-launcher pull request #1
Opened 2017-11-22 16:44 UTC by jfmengels

- Relancer la lambda lors d'un crash
- On lançait deux fois la lambda lorsqu'on lançait le binaire. On ne le lance plus qu'une fois maintenant

2017-11-23 13:19 UTC, godu requested changes
Pôs d’accord

2020-07-06 08:46 UTC, jfmengels commented
:wave: 
Je nettoye mes vieilles PRs :smile:

2020-07-06 08:46 UTC, closed without merging

2020-07-06 09:13 UTC, AdrieanKhisbe commented
👋  @jfmengels :wink:

(me rappelle meme plus quoi que c'est ce repo 😁 )

2020-07-06 10:44 UTC, godu commented
J'ai de vieux souvenir 😅